/**
 * A single AI-determined priority for the family.
 */
export type AIPriority = {
  id: string;
  title: string;
  explanation: string;
  priority: "High" | "Medium" | "Low";
};

/**
 * A resource recommended by the AI.
 *
 * The URL is optional because we will eventually
 * connect recommendations to verified resources.
 */
export type AIResource = {
  id: string;

  title: string;

  type:
    | "grant"
    | "government"
    | "insurance"
    | "therapy"
    | "school"
    | "financial"
    | "support"
    | "other";

  description: string;

  whyItMayHelp: string;

  eligibility?: string[];

  whatItMayCover?: string[];

  applicationSteps?: string[];

  documentsNeeded?: string[];

  url?: string;

  sourceName?: string;

  sourceType?:
    | "government"
    | "nonprofit"
    | "foundation"
    | "healthcare"
    | "other";

  lastVerified?: string;
};

/**
 * The AI's determination of what the family
 * should focus on right now.
 */
export type AICurrentFocus = {
  title: string;
  explanation: string;
};

/**
 * The AI's single most important next action.
 */
export type AINextStep = {
  title: string;
  description: string;
};

/**
 * A task recommended by the AI.
 *
 * AI is responsible for determining:
 * - What the task is
 * - Why it matters
 * - Priority
 * - Estimated time
 * - Resource, when appropriate
 *
 * The application is responsible for:
 * - Tracking completion
 * - Saving completion status
 */
export type AITask = {
  id: string;
  title: string;
  description: string;
  priority: "High" | "Medium" | "Low";
  estimatedTime: string;
  completed: boolean;
  resourceLink?: string;
};

/**
 * Complete personalized journey generated by AI.
 *
 * This is the primary object that drives
 * the Journey Dashboard.
 */
export type PersonalizedJourney = {
  summary: string;

  /**
   * The single most important area
   * for the family right now.
   */
  currentFocus: AICurrentFocus;

  /**
   * AI-ranked areas the family should focus on.
   */
  priorities: AIPriority[];

  /**
   * Specific actions/tasks recommended by AI.
   */
  tasks: AITask[];

  /**
   * Resources related to the AI recommendations.
   */
  resources: AIResource[];

  /**
   * The single most important next action.
   */
  nextStep: AINextStep;
};

/**
 * Metadata describing how and when
 * the AI journey was generated.
 */
export type AIJourneyMetadata = {
  version: number;

  generatedAt: number;

  reason:
    | "initial"
    | "tasks_completed"
    | "manual_refresh";
};

/**
 * Complete AI journey state.
 *
 * This is the object we will eventually save
 * with the user's account.
 */
export type AIJourney = {
  journey: PersonalizedJourney;

  metadata: AIJourneyMetadata;

  /**
   * IDs of tasks the family has completed.
   *
   * This allows the AI to understand what
   * the family has already accomplished.
   */
  completedTaskIds: string[];
};