import type { Task } from "../journeyEngine";

/**
 * A single AI-determined priority for the family.
 */
export type AIPriority = {
  id: string;

  title: string;

  explanation: string;

  priority: "High" | "Medium" | "Low";
};

/**
 * A resource recommended by the AI.
 *
 * The URL is optional because we will eventually
 * connect the AI to verified resources rather than
 * allowing it to invent links.
 */
export type AIResource = {
  id: string;

  title: string;

  description: string;

  url?: string;
};

/**
 * The AI's determination of what the family
 * should focus on right now.
 */
export type AICurrentFocus = {
  title: string;

  explanation: string;
};

/**
 * The AI's single most important next action.
 */
export type AINextStep = {
  title: string;

  description: string;
};

/**
 * Complete personalized journey generated by AI.
 *
 * This is the primary object that will drive
 * the Journey Dashboard.
 */
export type PersonalizedJourney = {
  /**
   * High-level explanation of the family's
   * current situation and recommended direction.
   */
  summary: string;

  /**
   * The most important area for the family
   * to focus on right now.
   */
  currentFocus: AICurrentFocus;

  /**
   * AI-ranked areas the family should focus on.
   */
  priorities: AIPriority[];

  /**
   * Specific actions/tasks recommended by AI.
   */
  tasks: Task[];

  /**
   * Resources related to the AI recommendations.
   */
  resources: AIResource[];

  /**
   * The single most important next action.
   */
  nextStep: AINextStep;
};

/**
 * Metadata about how/when the AI journey
 * was generated.
 */
export type AIJourneyMetadata = {
  version: number;

  generatedAt: number;

  reason:
    | "initial"
    | "tasks_completed"
    | "manual_refresh";
};

/**
 * Complete AI journey state.
 *
 * This is the object we will eventually save
 * with the user's journey.
 */
export type AIJourney = {
  journey: PersonalizedJourney;

  metadata: AIJourneyMetadata;
};