/**
 * A single AI-determined priority for the family.
 */
export type AIPriority = {
  id: string;
  title: string;
  explanation: string;
  priority: "High" | "Medium" | "Low";
};

/**
 * A specific action the AI recommends the family take.
 *
 * The goal is to answer:
 * - What should I do?
 * - Why does it matter?
 * - How do I do it?
 * - What should I do afterward?
 *
 * Guidance should remain concise and actionable.
 */
export type AIAction = {
  id: string;

  /**
   * Short description of the action.
   */
  title: string;

  /**
   * Why this action is relevant
   * to this particular family.
   */
  whyItMatters: string;

  /**
   * The specific thing the family
   * should do.
   */
  action: string;

  /**
   * Brief instructions explaining
   * how to complete the action.
   */
  howTo: string;

  /**
   * What the family should do after
   * completing this action.
   */
  nextStep?: string;

  /**
   * AI-determined importance.
   */
  priority: "High" | "Medium" | "Low";

  /**
   * Estimated amount of time required.
   */
  estimatedTime: string;

  /**
   * Related resource IDs.
   *
   * These should reference resources
   * returned in the resources array.
   */
  resourceIds?: string[];
};

/**
 * A resource recommended by the AI.
 *
 * Resources should eventually be connected
 * to verified resource data rather than
 * allowing the AI to invent resources or URLs.
 */
export type AIResource = {
  id: string;

  title: string;

  type:
    | "grant"
    | "government"
    | "insurance"
    | "therapy"
    | "school"
    | "financial"
    | "support"
    | "other";

  description: string;

  /**
   * Why this resource may be relevant
   * to this particular family.
   */
  whyItMayHelp: string;

  /**
   * Potential eligibility considerations.
   */
  eligibility?: string[];

  /**
   * Potential benefits or services
   * the resource may provide.
   */
  whatItMayCover?: string[];

  /**
   * Concise application or access steps.
   */
  applicationSteps?: string[];

  /**
   * Documents the family may need.
   */
  documentsNeeded?: string[];

  /**
   * Official or verified URL.
   */
  url?: string;

  /**
   * Organization providing the resource.
   */
  sourceName?: string;

  /**
   * Type of organization providing
   * the resource.
   */
  sourceType?:
    | "government"
    | "nonprofit"
    | "foundation"
    | "healthcare"
    | "other";

  /**
   * Date the resource was last verified.
   */
  lastVerified?: string;
};

/**
 * The AI's determination of what the family
 * should focus on right now.
 */
export type AICurrentFocus = {
  /**
   * Short, action-oriented focus statement.
   *
   * Example:
   * "Reduce out-of-pocket therapy costs"
   */
  title: string;

  /**
   * Brief explanation of why this is
   * the current focus.
   */
  explanation: string;
};

/**
 * The AI's single most important next action.
 */
export type AINextStep = {
  title: string;

  description: string;
};

/**
 * A task recommended by the AI.
 *
 * AI determines:
 * - What the task is
 * - Why it matters
 * - Priority
 * - Estimated time
 * - Resource, when appropriate
 *
 * The application determines:
 * - Completion status
 * - Saving completion status
 * - When completed tasks trigger reassessment
 */
export type AITask = {
  id: string;

  title: string;

  description: string;

  priority: "High" | "Medium" | "Low";

  estimatedTime: string;

  completed: boolean;

  resourceLink?: string;
};

/**
 * Complete personalized journey generated by AI.
 *
 * This is the primary object that drives
 * the Journey Dashboard.
 */
export type PersonalizedJourney = {
  /**
   * Short explanation of what the AI
   * understood about the family's situation.
   */
  summary: string;

  /**
   * The single most important area
   * for the family right now.
   */
  currentFocus: AICurrentFocus;

  /**
   * AI-ranked areas the family should
   * keep in focus.
   */
  priorities: AIPriority[];

  /**
   * Actionable recommendations.
   *
   * These answer:
   * What should I do?
   * Why?
   * How?
   * What's next?
   */
  actions: AIAction[];

  /**
   * Specific tasks recommended by AI.
   */
  tasks: AITask[];

  /**
   * Resources related to the AI
   * recommendations.
   */
  resources: AIResource[];

  /**
   * The single most important next action.
   */
  nextStep: AINextStep;
};

/**
 * Metadata describing how and when
 * the AI journey was generated.
 */
export type AIJourneyMetadata = {
  version: number;

  generatedAt: number;

  reason:
    | "initial"
    | "tasks_completed"
    | "manual_refresh";
};

/**
 * Complete AI journey state.
 *
 * This is the object we will eventually
 * save with the user's account.
 */
export type AIJourney = {
  journey: PersonalizedJourney;

  metadata: AIJourneyMetadata;

  /**
   * IDs of tasks the family has completed.
   *
   * This allows the AI to understand what
   * the family has already accomplished.
   */
  completedTaskIds: string[];
};